/* ==========================================================================
   snippets.js — modeles de fichiers prets a l'emploi
   ========================================================================== */
(function (global) {
  'use strict';

  global.PySnippets = [
    {
      title: 'Script CLI (argparse)',
      desc: 'Squelette de programme en ligne de commande',
      file: 'cli.py',
      code: [
        '"""Outil en ligne de commande."""',
        'import argparse',
        'import sys',
        '',
        '',
        'def build_parser() -> argparse.ArgumentParser:',
        '    p = argparse.ArgumentParser(description="Decrivez votre outil ici.")',
        '    p.add_argument("entree", nargs="?", default="-", help="fichier d\'entree")',
        '    p.add_argument("-n", "--nombre", type=int, default=1)',
        '    p.add_argument("-v", "--verbose", action="store_true")',
        '    return p',
        '',
        '',
        'def main(argv=None) -> int:',
        '    args = build_parser().parse_args(argv)',
        '    if args.verbose:',
        '        print("arguments :", vars(args), file=sys.stderr)',
        '    for i in range(args.nombre):',
        '        print(i, args.entree)',
        '    return 0',
        '',
        '',
        'if __name__ == "__main__":',
        '    raise SystemExit(main())',
        ''
      ].join('\n')
    },
    {
      title: 'Classe + tests',
      desc: 'unittest integre, executable directement',
      file: 'test_compte.py',
      code: [
        'import unittest',
        '',
        '',
        'class Compte:',
        '    def __init__(self, solde: float = 0.0):',
        '        self.solde = float(solde)',
        '',
        '    def depot(self, montant: float) -> float:',
        '        if montant <= 0:',
        '            raise ValueError("montant positif attendu")',
        '        self.solde += montant',
        '        return self.solde',
        '',
        '    def retrait(self, montant: float) -> float:',
        '        if montant > self.solde:',
        '            raise ValueError("solde insuffisant")',
        '        self.solde -= montant',
        '        return self.solde',
        '',
        '',
        'class TestCompte(unittest.TestCase):',
        '    def setUp(self):',
        '        self.c = Compte(100)',
        '',
        '    def test_depot(self):',
        '        self.assertEqual(self.c.depot(50), 150)',
        '',
        '    def test_retrait_excessif(self):',
        '        with self.assertRaises(ValueError):',
        '            self.c.retrait(500)',
        '',
        '',
        'if __name__ == "__main__":',
        '    unittest.main(argv=["pyterm"], exit=False, verbosity=2)',
        ''
      ].join('\n')
    },
    {
      title: 'Fichiers & JSON',
      desc: 'pathlib, lecture/ecriture, json',
      file: 'fichiers.py',
      code: [
        'import json',
        'from pathlib import Path',
        '',
        'dossier = Path("donnees")',
        'dossier.mkdir(exist_ok=True)',
        '',
        'cible = dossier / "notes.json"',
        'notes = {"algebre": 15.5, "python": 18, "reseaux": 12}',
        'cible.write_text(json.dumps(notes, indent=2, ensure_ascii=False), encoding="utf-8")',
        '',
        'relu = json.loads(cible.read_text(encoding="utf-8"))',
        'moyenne = sum(relu.values()) / len(relu)',
        '',
        'print("Fichier :", cible.resolve())',
        'print("Contenu :", relu)',
        'print(f"Moyenne : {moyenne:.2f}")',
        '',
        'for p in sorted(dossier.iterdir()):',
        '    print("-", p.name, p.stat().st_size, "octets")',
        ''
      ].join('\n')
    },
    {
      title: 'Asyncio',
      desc: 'taches concurrentes avec async / await',
      file: 'async_demo.py',
      code: [
        'import asyncio',
        'import time',
        '',
        '',
        'async def travail(nom: str, duree: float) -> str:',
        '    await asyncio.sleep(duree)',
        '    return f"{nom} termine en {duree:.1f}s"',
        '',
        '',
        'async def main() -> None:',
        '    debut = time.perf_counter()',
        '    resultats = await asyncio.gather(',
        '        travail("A", 0.4),',
        '        travail("B", 0.2),',
        '        travail("C", 0.6),',
        '    )',
        '    for r in resultats:',
        '        print(r)',
        '    print(f"total : {time.perf_counter() - debut:.2f}s")',
        '',
        '',
        'asyncio.run(main())',
        ''
      ].join('\n')
    },
    {
      title: 'Calcul numerique',
      desc: 'numpy — installe automatiquement',
      file: 'numerique.py',
      code: [
        '# Necessite numpy : onglet Paquets, ou  !pip install numpy',
        'import numpy as np',
        '',
        'rng = np.random.default_rng(42)',
        'a = rng.normal(loc=10, scale=2.5, size=(4, 5))',
        '',
        'print(a.round(2))',
        'print()',
        'print("moyenne  :", a.mean().round(3))',
        'print("ecart-type:", a.std().round(3))',
        'print("par ligne :", a.mean(axis=1).round(2))',
        '',
        'b = np.linalg.inv(a[:4, :4] + np.eye(4) * 5)',
        'print()',
        'print("inverse   :")',
        'print(b.round(3))',
        ''
      ].join('\n')
    },
    {
      title: 'Generateurs & itertools',
      desc: 'flux paresseux, pipelines',
      file: 'generateurs.py',
      code: [
        'import itertools',
        'from typing import Iterator',
        '',
        '',
        'def fibonacci() -> Iterator[int]:',
        '    a, b = 0, 1',
        '    while True:',
        '        yield a',
        '        a, b = b, a + b',
        '',
        '',
        'premiers_20 = list(itertools.islice(fibonacci(), 20))',
        'print(premiers_20)',
        '',
        'pairs = [n for n in premiers_20 if n % 2 == 0]',
        'print("pairs :", pairs)',
        '',
        'groupes = {',
        '    cle: list(grp)',
        '    for cle, grp in itertools.groupby(sorted(premiers_20, key=lambda n: n % 3),',
        '                                      key=lambda n: n % 3)',
        '}',
        'for reste, valeurs in groupes.items():',
        '    print(f"reste {reste} : {valeurs}")',
        ''
      ].join('\n')
    },
    {
      title: 'Chronometrage',
      desc: 'mesurer et comparer deux approches',
      file: 'benchmark.py',
      code: [
        'import timeit',
        '',
        'SETUP = "donnees = list(range(20000))"',
        '',
        'candidats = {',
        '    "boucle":         "total = 0\\nfor n in donnees: total += n * n",',
        '    "comprehension":  "total = sum([n * n for n in donnees])",',
        '    "generateur":     "total = sum(n * n for n in donnees)",',
        '    "map":            "total = sum(map(lambda n: n * n, donnees))",',
        '}',
        '',
        'resultats = {',
        '    nom: timeit.timeit(code, setup=SETUP, number=50)',
        '    for nom, code in candidats.items()',
        '}',
        '',
        'reference = min(resultats.values())',
        'for nom, duree in sorted(resultats.items(), key=lambda kv: kv[1]):',
        '    barre = "#" * int(30 * duree / max(resultats.values()))',
        '    print(f"{nom:<14} {duree * 1000:7.1f} ms  x{duree / reference:4.2f}  {barre}")',
        ''
      ].join('\n')
    }
  ];
})(window);
